[package]
name = "openprod-core"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde.workspace = true
rmp-serde.workspace = true
uuid.workspace = true
ed25519-dalek.workspace = true
rand.workspace = true
thiserror.workspace = true
blake3.workspace = true
